version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: tracking-stress-tool-db
    restart: always
    environment:
      POSTGRES_DB: tracking_events
      POSTGRES_USER: trackuser
      POSTGRES_PASSWORD: trackpass
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db_init.sql:/docker-entrypoint-initdb.d/db_init.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U trackuser -d tracking_events"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: